### ISSUE TITLE
Update for Symfony 3.3+ required

### ISSUE THREAD

**Issue by lbm-services** [Bee-Lab/BeelabUserBundle#9]
> php.INFO: User Deprecated: Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "beelab_user.manager" service to "Beelab\UserBundle\Manager\UserManager" instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the \"beelab_user.manager\" service to \"Beelab\\UserBundle\\Manager\\UserManager\" instead. at /mnt/shared/bbtdb/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php:351)"} []

**Comment by garak** [comment]
This should be fixed. Can you check?
